//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此原始程式碼由 xsd 版本=4.6.1055.0 自動產生。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class root {
    
    private rootCarInfo[] carInfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CarInfo")]
    public rootCarInfo[] CarInfo {
        get {
            return this.carInfoField;
        }
        set {
            this.carInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootCarInfo {
    
    private float latField;
    
    private bool latFieldSpecified;
    
    private float lngField;
    
    private bool lngFieldSpecified;
    
    private rootCarInfoPropertys[] propertysField;
    
    private string uuidField;
    
    private string timestampField;
    
    /// <remarks/>
    public float Lat {
        get {
            return this.latField;
        }
        set {
            this.latField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LatSpecified {
        get {
            return this.latFieldSpecified;
        }
        set {
            this.latFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public float Lng {
        get {
            return this.lngField;
        }
        set {
            this.lngField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LngSpecified {
        get {
            return this.lngFieldSpecified;
        }
        set {
            this.lngFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Propertys")]
    public rootCarInfoPropertys[] Propertys {
        get {
            return this.propertysField;
        }
        set {
            this.propertysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uuid {
        get {
            return this.uuidField;
        }
        set {
            this.uuidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootCarInfoPropertys {
    
    private short lV_IDField;
    
    private short lV_ValueField;
    
    /// <remarks/>
    public short LV_ID {
        get {
            return this.lV_IDField;
        }
        set {
            this.lV_IDField = value;
        }
    }
    
    /// <remarks/>
    public short LV_Value {
        get {
            return this.lV_ValueField;
        }
        set {
            this.lV_ValueField = value;
        }
    }
}
